### ISSUE TITLE
Assigned background color in bcolor() is invariant, so pre-compute it

### ISSUE THREAD

**Issue by jbmonroe** [mburakerman/hrjs#3]
```  var data_hr = selector.querySelectorAll('[data-hr]');
  var bkC = (typeof this.options.backgroundColor !== 'undefined') ? 
              this.options.backgroundColor :  
              this.defaultOptions.backgroundColor;
  for (var j = 0; j < data_hr.length; j++) {
      data_hr[j].style.backgroundColor = bkC;
  }
```
At the cost of increasing the time spent in the constructor, `this.options` could be a merge between default options and the incoming options; in that case, `defaultOptions` should be static to `HR`, not part of the prototype since `defaultOptions` is invariant during the lifetime of an instance.  You can use `Object.assign` to do the (possibly with a polyfill for IE11).

**Comment by mburakerman** [comment]
I have put it to prototype because i am checking _basicly_  if `options` are `undefined` and if only `this.options.replaceWith` is undefined. So in both condition, i have to check `backgroundColor`. 

To not make same loop for  `backgroundColor`, i created a method and called it in that both condition.

**Comment by jbmonroe** [comment]
I'm not sure you took my point.  The `defaultOptions` values never vary throughout the life of the instance, therefore they don't need to be associated with an instance.  Therefore they can be static to the class, rather than provided on a per-instance basis.  (Assigned as a member of the function HR rather than as a part of the prototype.)

In the constructor 

`this.options = Object.assign({},HR.defaultOptions,options);`

will cover all the instances you indicate.  If `options.replaceWith` is `undefined` or `null`, it will survive as `undefined` or `null` because that's what you have in the default.

I agree that one requires a polyfill for `Object.assign` in order to do this.

I'm doing a pure ES6 version to keep myself busy this afternoon, and I will use it with all your test cases to determine if I'm correct in my assertions.

**Comment by mburakerman** [comment]
Ah, i understand now. Also made an example with your help below.
I think this code does what you say think.

Also, here a [jsfiddle ](https://jsfiddle.net/wcLaoheL/)to check it in `hr.js`. Works normally for now.


```
  this.options = Object.assign({}, HR.defaultOptions, options);

  this.bcolor = function(selector) {
    var data_hr = selector.querySelectorAll('[data-hr]');
    for (var j = 0; j < data_hr.length; j++) {
      data_hr[j].style.backgroundColor = this.options.backgroundColor
    }
  }
```
