### ISSUE TITLE
Regex support

### ISSUE THREAD

**Issue by saeidzebardast** [mburakerman/hrjs#6]
Hi, 

Does ```hr.js``` support regex for finding text?

**Comment by mburakerman** [comment]
I don't understand what you mean. As it is said in description, `hr.js` is for highlighting and replacing text. 
If you mean finding a specific text, just use [highlight ](https://github.com/mburakerman/hrjs#highlight-example) option.

**Comment by ziadkh0** [comment]
I think he means to do something like this (which he currently can do)
```js
new HR("#mytext", {
  highlight: "d.*or",
  replaceWith: "cat",
  backgroundColor: "#B4FFEB"
}).hr();
```

But this shouldn't be the case, the `highlight` value should be escaped as it's not expected to be a regex (see [escape-string-regexp](https://github.com/sindresorhus/escape-string-regexp)).
Also the replacement string should be escaped ([some characters a special](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter)).

A better solution for supporting regex is to allow the user to pass a regex directly:
```js
new HR("#mytext", {
  highlight: /d.*or/i,
  replaceWith: "cat",
  backgroundColor: "#B4FFEB"
}).hr();
```

**Comment by mburakerman** [comment]
I understand now, thank you @zaygraveyard.
For now, it does not support @saeidzebardast.

**Comment by saeidzebardast** [comment]
@zaygraveyard thank you for explaining my question. That's what I meant.
